_pythonmac seem to work in virtual env with MacOS 10.12

diff --git a/pythonmac b/pythonmac
--- a/pythonmac
+++ b/pythonmac
@@ -1,20 +1,26 @@
 #!/bin/bash
 
-if ! [ -x "$(command -v brew)" ]; then
-  echo 'Error: this script is intended for Mac, not linux.' >&2
-  exit 1
-fi
-
+#if ! [ -x "$(command -v brew)" ]; then
+#  echo 'Error: this script is intended for Mac, not linux.' >&2
+#  exit 1
+#fi
+#
 
 # --- Finding Framework python
 FRAMEWORK_PYTHON_ROOT="/Library/Frameworks/Python.framework/Versions"
-if [ ! -f $FRAMEWORK_PYTHON_ROOT ]; then
-    echo "Framework not found in /Library/. Trying in /FRAMEWORK"
-    FRAMEWORK__PYTHON_ROOT="/System/Library/Frameworks/Python.framework/Versions"
-    if [ ! -f $FRAMEWORK_PYTHON_ROOT ]; then
-        echo "Framework not found in /System. Trying in $(brew --prefix)" 
+echo $FRAMEWORK_PYTHON_ROOT
+if [ ! -d $FRAMEWORK_PYTHON_ROOT ]; then
+    echo "Framework not found in /Library/. Trying in /System"
+    FRAMEWORK_PYTHON_ROOT="/System/Library/Frameworks/Python.framework/Versions"
+    echo $FRAMEWORK_PYTHON_ROOT
+    if [ ! -d $FRAMEWORK_PYTHON_ROOT ]; then
+        echo "Framework not found in /System. Trying in brew"
         PYSUBVER="$(python --version 2>&1 | cut -d ' ' -f2)"  # e.g., 2.7.10
         FRAMEWORK_PYTHON_ROOT="$(brew --prefix)/Cellar/python/$PYSUBVER/Frameworks/Python.framework/Versions"
+	if [ ! -d $FRAMEWORK_PYTHON_ROOT ]; then
+		echo "Error: Cannot find a system python installation"
+		exit 1
+        fi
     fi
 fi
 echo "Framework python path: $FRAMEWORK_PYTHON_ROOT"
@@ -23,10 +29,7 @@ echo "Framework python path: $FRAMEWORK_PYTHON_ROOT"
 
 # --- Python exe
 PYVER=2.7
-FRAMEWORK_PYTHON="$FRAMEWORK_PYTHON_ROOT/bin/python$PYVER"
-if [ ! -f FRAMEWORK_FRAMEWORK_PYTHON_ROOT ]; then
-    echo "Not found in /Library/. Trying in /FRAMEWORK"
-
+FRAMEWORK_PYTHON="$FRAMEWORK_PYTHON_ROOT/$PYVER/bin/python$PYVER"
 echo "Framework python:      $FRAMEWORK_PYTHON"
 
 
@@ -50,7 +53,7 @@ else
     VENV_SITE_PACKAGES="$VIRTUAL_ENV/lib/python$PYVER/site-packages"
 
     # Ensure wx.pth is set up in the virtualenv
-    cp "/Library/Python/$PYVER/site-packages/wxredirect.pth" "$VENV_SITE_PACKAGES/wx.pth"
+    #cp "/Library/Python/$PYVER/site-packages/wxredirect.pth" "$VENV_SITE_PACKAGES/wx.pth"
 
     # Use the Framework Python to run the app
     export PYTHONHOME=$VIRTUAL_ENV
